apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-app-101
spec:
  components:
    - name: helloworld
      type: webservice
      properties:
        image: artifactory.corp.olacabs.com:5002/helloworld-python:v1
        env:
          - name: "TARGET"
            value: "world"
        ports:
         - port: 8080
           expose: true
      traits:
        - type: scaler
          properties:
            replicas: 1